const express=require("express")
const cors=require("cors")
const dotenv=require("dotenv")
dotenv.config()
require("./db.js")
const app=express()
app.use(cors())
app.use(express.json())
app.use("/uploads",express.static("uploads/"))
const organizationctrl=require ("./controllers/organizationcontroller.js")
app.use("/organization",organizationctrl)
const productctrl=require ("./controllers/productcontrollers.js")
app.use("/product",productctrl)
const userctrl=require ("./controllers/usercontroller.js")
app.use("/user",userctrl)
const adminctrl=require("./controllers/admincontroller.js")
app.use("/admin",adminctrl)
app.listen(8080,()=>{
    console.log("server running at port number:8080")
})
